pipeline {
    agent any
      tools {
        maven 'Maven-3.9.8' // Ensure this matches the name of the Maven installation in Jenkins
    }

    stages {
        stage('Build') {
            steps {
                sh 'mvn -B -DskipTests clean package'
            }
        }
        stage('Test') {
            steps {
                sleep(3)
                sh 'mvn test'
            }
            post {
                always {
                    junit 'target/surefire-reports/*.xml'
                }
            }
        }
        stage('Deliver') {
            steps {
                sh './jenkins/scripts/deliver.sh'
            }
        }
        stage('Complete'){
            steps{
                echo"Job Complete!"
            }
        }
        stage('Build Challenge 3'){
            steps{

                build 'Challenge 3'
            }     
        }
    }
}
